
//--------------------------------------------------
//// .gitignore

//// POWERSHELL
// # add gitignore file in current directory
dotnet new gitignore



//--------------------------------------------------
//// EF Migration - Code First Approach

/*
first create:

1. DEFINE DATABASE in *Context.cs:
    - define tables (DbSet)
    - define iserts (HasData)
    - or load configurations from other files (OnModeCreating() {ApplyConfiguration})

2. DEFINE MODELS in Models/MODEL_NAME.cs files:
    - use attributes

3. RUN MIGRATION:
    dotnet tool install --global dotnet-ef
    dotnet ef migrations add my_migration_name
    dotnet ef database update 
*/

//// POWERSHELL
dotnet tool install --global dotnet-ef
dotnet ef migrations add my_migration_name
dotnet ef migrations remove
dotnet ef database update 
dotnet ef database drop

// or Package Manager Console
Add-Migration <name> -Context <ContextClassName>
Update-Database -Context <ContextClassName>



//--------------------------------------------------
//// EF - Database First Approach

/*
1. use SQL to create and load database
2. run Scaffold-DbContext to create DbContext
*/


// 2. run Scaffold-DbContext to create DbContext
//#####
//## Scaffold-DbContext using Package Manager Console

PackageManagerConsole: 
    Tools > NuGet Packet Manager > Package Manager Console


# Scaffold-DbContext
Scaffold-DbContext "connectionStringOrConnectionStringName" providerPackagename

# this will connect to db using the connection name and provider and create .cs classes for models in the root of the project
Scaffold-DbContext "Name=ConnectionStrings:Default" Microsoft.EntityFrameworkCore.SqlServer
Scaffold-DbContext "Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=apbd; Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer

# -Tables "tbl1", "tbl2" - will create models only for those Tables
# -OutputDir dirName - select dir for classes for models
# -ContextDir Data - select dir for ApbdContext.cs class

Scaffold-DbContext "Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=apbd; Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer -ContextDir Data -OutputDir Models -Tables "Client","Client_Trip","Trip","Country_Trip","Country"

Scaffold-DbContext "Name=ConnectionStrings:Default" Microsoft.EntityFrameworkCore.SqlServer -ContextDir Data -OutputDir Models -Tables "Client","Client_Trip","Trip","Country_Trip","Country"








//--------------------------------------------------
//// Program.cs

...after builder.Services.AddSwaggerGen();
// mine

builder.Services.AddScoped<ITripsRepository, TripsRepository>();
builder.Services.AddScoped<IClientRepository, ClientRepository>();
builder.Services.AddDbContext<ApbdContext>();
builder.Services.AddDbContext<ApbdContext>(options =>
{
    options.UseSqlServer(builder.Configuration.GetConnectionString("Default"));
});

//// mine end
...before var app = builder.Build();


//--------------------------------------------------
//// launchSettings.json
{
 "profiles": {
   "http": {
     "commandName": "Project",
     "dotnetRunMessages": true,
     "launchBrowser": true,
     "launchUrl": "swagger",
     "applicationUrl": "http://localhost:5001",
     "environmentVariables": {
       "ASPNETCORE_ENVIRONMENT": "Development"
     }
   }
 }
}


//--------------------------------------------------
//// appsettings.json
{
 "Logging": {
   "LogLevel": {
     "Default": "Information",
     "Microsoft.AspNetCore": "Warning"
   }
 },
 "AllowedHosts": "*",
 "ConnectionStrings": {
   "Default": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=apbd;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
 }
}


//--------------------------------------------------
//// appsettings.Development.json
// default content, dont change it


//--------------------------------------------------
// ADD CONTROLLER
- add controller:
    > right click Controller folder > add > Controller > API > Empty Controller > TripsController.cs


//--------------------------------------------------
// CREATE NEW PROJECT IN VS
- create new project:
    new project "asp.net core web api"
        - .NET 7
        - disable "Configure for HTTPS"
        - leave rest default
    - delete unused dummy demo classes generated by vs
    - launchSettings.json modify:
            - delete top schema chunk, leave only profiles
            - delete other profiles, lesave only http profile
            - change port
            - can rename profile

//--------------------------------------------------
//  install EntityFrameworkCore and tools
- Tools > NuGet Packet Manager > Manage NuGet packages for solution > Browse
- install:
    - Microsoft.EntityFrameworkCore             - framework
    - Microsoft.EntityFrameworkCore.SqlServer   - provider for mssqls
    - Microsoft.EntityFrameworkCore.Tools       - for Scaffold-DbContext


Microsoft.EntityFrameworkCore.Tools that we will use and need to install on KOLOKWIUM:
    Scaffold-DbContext
    Add-Migration
    Update-Database







//--------------------------------------------------
//--------------------------------------------------
//-- NIE NA KOLOSA
//--------------------------------------------------
//--------------------------------------------------
//--------------------------------------------------





//--------------------------------------------------
// make connection string secret

- make connection string secret - this is for production, NOT for the exercise
    > right click on asp project in solution explorer
    > manage user secrets
    > move the "ConnectionStrings" chunk from appsettings.json into secrets.json file
    - this is for production, NOT for the exercise
    - https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli

